function [trainedModel, validationRMSE] = trainRegressionModel(trainingData)
%  TRAINREGRESSIONMODEL [trainedModel, validationRMSE] = trainRegressionModel(trainingData)
% 
% Returns a trained regression model and its RMSE. This code recreates the model 
% trained in Regression Learner app. Use the generated code to automate training 
% the same model with new data, or to learn how to programmatically train models.
% 
% Input: trainingData: A table containing the same predictor and response columns 
% as those imported into the app.
% 
% Output: trainedModel: A struct containing the trained regression model. The 
% struct contains various fields with information about the trained model.
% 
% trainedModel.predictFcn: A function to make predictions on new data.
% 
% validationRMSE: A double containing the RMSE. In the app, the History list 
% displays the RMSE for each model.
% 
% Use the code to train the model with new data. To retrain your model, call 
% the function from the command line with your original data or new data as the 
% input argument trainingData.
% 
% For example, to retrain a regression model trained with the original data 
% set T, enter: [trainedModel, validationRMSE] = trainRegressionModel(T)
% 
% To make predictions with the returned 'trainedModel' on new data T2, use yfit 
% = trainedModel.predictFcn(T2)
% 
% T2 must be a table containing at least the same predictor columns as used 
% during training. For details, enter: trainedModel.HowToPredict
% Auto-generated by MATLAB on 28-Oct-2020 13:21:16
% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'Car_Truck', 'EngDisp', 'RatedHP', 'Transmission', 'Weight', 'Comp', 'AxleRatio', 'EVSpeedRatio', 'City_Highway', 'CO2'};
predictors = inputTable(:, predictorNames);
response = inputTable.MPG;
isCategoricalPredictor = [true, false, false, true, false, false, false, false, true, false];
% Train a regression model
% This code specifies all the model options and trains the model.
responseScale = iqr(response);
if ~isfinite(responseScale) || responseScale == 0.0
    responseScale = 1.0;
end
boxConstraint = responseScale/1.349;
epsilon = responseScale/13.49;
regressionSVM = fitrsvm(...
    predictors, ...
    response, ...
    'KernelFunction', 'gaussian', ...
    'PolynomialOrder', [], ...
    'KernelScale', 3.2, ...
    'BoxConstraint', boxConstraint, ...
    'Epsilon', epsilon, ...
    'Standardize', true);
% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
svmPredictFcn = @(x) predict(regressionSVM, x);
trainedModel.predictFcn = @(x) svmPredictFcn(predictorExtractionFcn(x));
% Add additional fields to the result struct
trainedModel.RequiredVariables = {'AxleRatio', 'CO2', 'Car_Truck', 'City_Highway', 'Comp', 'EVSpeedRatio', 'EngDisp', 'RatedHP', 'Transmission', 'Weight'};
trainedModel.RegressionSVM = regressionSVM;
trainedModel.About = 'This struct is a trained model exported from Regression Learner R2020a.';
trainedModel.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appregression_exportmodeltoworkspace'')">How to predict using an exported model</a>.');
% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'Car_Truck', 'EngDisp', 'RatedHP', 'Transmission', 'Weight', 'Comp', 'AxleRatio', 'EVSpeedRatio', 'City_Highway', 'CO2'};
predictors = inputTable(:, predictorNames);
response = inputTable.MPG;
isCategoricalPredictor = [true, false, false, true, false, false, false, false, true, false];
% Perform cross-validation
KFolds = 5;
cvp = cvpartition(size(response, 1), 'KFold', KFolds);
% Initialize the predictions to the proper sizes
validationPredictions = response;
for fold = 1:KFolds
    trainingPredictors = predictors(cvp.training(fold), :);
    trainingResponse = response(cvp.training(fold), :);
    foldIsCategoricalPredictor = isCategoricalPredictor;
    
    % Train a regression model
    % This code specifies all the model options and trains the model.
    responseScale = iqr(trainingResponse);
    if ~isfinite(responseScale) || responseScale == 0.0
        responseScale = 1.0;
    end
    boxConstraint = responseScale/1.349;
    epsilon = responseScale/13.49;
    regressionSVM = fitrsvm(...
        trainingPredictors, ...
        trainingResponse, ...
        'KernelFunction', 'gaussian', ...
        'PolynomialOrder', [], ...
        'KernelScale', 3.2, ...
        'BoxConstraint', boxConstraint, ...
        'Epsilon', epsilon, ...
        'Standardize', true);
    
    % Create the result struct with predict function
    svmPredictFcn = @(x) predict(regressionSVM, x);
    validationPredictFcn = @(x) svmPredictFcn(x);
    
    % Add additional fields to the result struct
    
    % Compute validation predictions
    validationPredictors = predictors(cvp.test(fold), :);
    foldPredictions = validationPredictFcn(validationPredictors);
    
    % Store predictions in the original order
    validationPredictions(cvp.test(fold), :) = foldPredictions;
end
% Compute validation RMSE
isNotMissing = ~isnan(validationPredictions) & ~isnan(response);
validationRMSE = sqrt(nansum(( validationPredictions - response ).^2) / numel(response(isNotMissing) ));