xs=0;
zs=0;
xg=0:10:1000;
zg=zeros(size(xg));
V=1000;
f=10;
w=2*pi*f;
ks=2*pi/(V/f)/2;
kg=sqrt((w/V).^2-ks);
rs=[xs(:).';zs(:).'];
rg=[xg(:).';zg(:).'];
xg=xg+100;zg=zg+100;
Go=wavefront(rs,rg,ks,kg,w);
%P=exp(+i*(ks*xg+kg*abs(zg-zs)));
figure
subplot(211),plot(xg,real(Go))
subplot(212),plot(xg,imag(Go))
P=Go+Go;