function peo(N,G,RXX,POT)

C***********************************************************************
C	PROPOSITO : GERAR O OPERADOR WIENER DE PREDICAO UNITARIA
C
C	DESCRICAO DOS PARAMETROS:
C		ENTRADA:
C			N  =  N@ DE COEFICIENTES DO OPERADOR DE PREDICAO
C			RXX=  COEFICIENTES DA FUNCAO DE AUTOCORRELACAO
C			ALF = LUZ BRANCA ( > 1., EX: 1.0001)
C		SAIDA  :
C			G  =  COEFICIENTES DO OPERADOR DE PREDICAO
C			POT=  ENERGIA DO ERRO DE PREDICAO
C	OBSERVACAO:  O NUMERO DE COEFICIENTES RXX DEVE SER  MAIOR QUE N
C
C	SUBROTINAS REQUERIDAS:	NENHUMA
C
C	METODO:   RECURSAO LEVINSON SOBRE O SISTEMA
C		      [Rxx]g = rxx
C			   -   -      ONDE
C		Rxx  =	MATRIZ TOEPLITZ SIMETRICA
C		g    =	COEF. DO OPERADOR DE PREDICAO
C		rxx  =	(r1, r2,........, rN+1) COEF. AUTOCORRELACAO
C
C	AUTOR: MILTON J. PORSANI		PPPG-UFBA  JULHO/84
C
**********************************************************************
	implicit real*8 (A-H,O-Z)
	real*8 G(1),RXX(1)
	POT = RXX(1)
	DO 1 J=1,N
		SG1 = RXX(J+1)
	DO 2 I=1,J-1
		JI = J-I
2		SG1 = SG1 + G(I)*RXX(JI+1)
	G(J) = -SG1/POT
	POT = POT+ SG1*G(J)
	DO 3 I=1,INT(J/2)
		JI=J-I
		GA1 = G(JI)
		G(JI) = GA1   + G(J)*G(I)
		IF(JI.EQ.I) GO TO 3
		G(I) = G(I)   + G(J)*GA1
3	CONTINUE
1	CONTINUE
	RETURN
	END


