% This program reads the index.bin file generated by radint_sparse to
% generate the sparse matrix S that maps from points to hyperbolas
% in order to see the eigenspectra
% Daniel Trad UBC- Feb 2000

NT=64;
NX=26;
NP=30;


fid=fopen('/home/dtrad/work/index.bin','rb');
IJ=fread(fid,'ushort');
fclose(fid);

fid=fopen('/home/dtrad/work/weight.bin','rb');
W=fread(fid,'float');
fclose(fid);

[M N]=size(IJ);
ij=reshape(IJ,M/2,2);
clear IJ
s=ones(M/2,1);

S=sparse(ij(:,1)+1,ij(:,2)+1,s);
clear s
[M N]=size(S);
clear ij;
ip=15;
it=50;
[xx]=impulse(S,it,ip,NT,NX);
%load eigenvalhypradon
%e=svds(S,20);

 
subplot(221),wigb(full(xx)),title('Impulse Function')
clear xx;
%subplot(222),plot(e),title('Eigenvalues')
subplot(223),spy(S),title('Sparse hyperbolic Radon operator')
subplot(224),plot(W);








